#!/usr/bin/env bash
# Install ans start nginx server
sudo apt-get -y install nginx
sudo service nginx start
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx restart
