#!/usr/bin/env bash
#Configure Nginx server so that /redirect_me is redirecting to another page.

sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo "Hello World!" >> /var/www/html/index.html

sudo chown -R $USER:$USER /var/www/html
sudo chmod -R 755 /var/www

sudo sed -i '37i\rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

sudo service nginx start
