#!/usr/bin/env bash
# Displays "To infinity and beyond" indefinitely with
# sleep 2 in between each iteration.
# and Displays "I am invincible!!!" in between each iteration.
while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'ec
